### ISSUE TITLE
most pcaps come back empty

### ISSUE THREAD

**Issue by ben-jones** [iclab/centinel#145]
It's unclear exactly what's happening, but we don't specify an interface to capture on by default, so we may be getting a loopback interface or something. For more details, talk to @jakubd

**Comment by phillipa** [comment]
Is this just for the Pis or for VPN end points too?

**Comment by rpanah** [comment]
Some older machines don't have tcpdump installed by default. That could be the reason. We fixed this problem on one of them by installing tcpdump.

**Comment by ben-jones** [comment]
that makes sense. However, there still appears to be an issue on some RPIs in the field. I will touch base with @jakubd for more info

**Comment by sneft** [comment]
In many cases on the Pis if I run a test and get the "Input file not found" message, it will continue to run the test with an empty list and thus create an empty pcap. Perhaps that accounts for some of the empty pcaps.

**Comment by rpanah** [comment]
@sneft, that could be the cause in some cases, but I suspect that in the case of the Raspberry Pis, `tcpdump` is simply not installed by default (`sudo apt-get install tcpdump` to install).

**Comment by sneft** [comment]
Ok, that's probably true for some of the devices. However I do have a case of a Pi with tcpdump installed, running centinel-dev 0.1.5.3 which seems to consistently create empty pcaps. I'm happy to help with troubleshooting.

**Comment by rpanah** [comment]
@sneft, I'll email you for troubleshooting.

**Comment by rpanah** [comment]
We still have that issue on some machines that have tcpdump installed. It might be that the tests aren't being run, which might be due to missing dependencies. I'm trying to enhance error reporting so that centinel includes missing dependencies in the results.

**Comment by Tikitaco** [comment]
I was able to get populated pcaps on my machine by changing the tcpdump_params line in ~/.centinel/config.ini from a string to an array. The old line was:
 "tcpdump_params": "-i any". 
After changing it to:
"tcpdump_params": ["-i","any"]
the pcaps stopped returning empty. Can we test this on some other machines/Pis to see if this fixes the issue?

**Comment by sneft** [comment]
I just tried this on an rpi in the field and it worked - the pcap went from 14 bytes to 38 megs in a before-and-after test.

**Comment by rpanah** [comment]
I've patched this. It'll be available in the new version.

**Comment by feamster** [comment]
Seems pretty amazing that such a basic bug is being caught only now.  Maybe there should be a testing and monitoring framework.

On another note, shipping back 38 MB from a single test sounds excessive, particularly in countries that have data caps.  We went to great lengths in BISmark to limit this kind of data usage. I wonder if we should be taking steps here to curtail the usage.

**Comment by phillipa** [comment]
I think part of it was that the experiment was implemented but we weren’t really looking at the outputs.

It should be easy enough to write a script that goes over results as they come back and flags if they are ‘good’ or not to help us track when a bunch of ‘bad’ results come back.

Agree about the data. On one hand we could limit our use of the pcap primitive … on the other ‘pcaps or it didn’t happen’. We could run basic tests over the pcaps on the Pis (e.g., testing for sequence number anomalies, RSTs) and send those results back, then issue subsequent measurements that send pcaps back if it looks like there are anomalies that warrant further investigation.


Phillipa Gill, Assistant Professor
Dept. of Computer Science
Stony Brook University, SUNY
http://www.cs.stonybrook.edu/~phillipa <http://www.cs.stonybrook.edu/~phillipa>
http://www.nrg.cs.stonybrook.edu <http://www.nrg.cs.stonybrook.edu/>
